# Generated by Django 5.0.3 on 2024-03-27 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_anon_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymizedInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pub_date", models.DateTimeField(verbose_name="time submitted")),
                ("choice_dict", models.TextField()),
                ("anon_input_text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="InitialInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_text", models.TextField()),
                ("pub_date", models.DateTimeField(verbose_name="time submitted")),
                ("ner_dict", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="AnonymizedOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pub_date", models.DateTimeField(verbose_name="time submitted")),
                ("llm_output_text", models.TextField()),
                ("unmasked_output_text", models.TextField()),
                (
                    "anon_input",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="llm_anon_app.anonymizedinput",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvalQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=200)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                (
                    "anon_output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="llm_anon_app.anonymizedoutput",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvalAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.CharField(max_length=200)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="llm_anon_app.evalquestion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="anonymizedinput",
            name="initial_input",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="llm_anon_app.initialinput",
            ),
        ),
    ]
