# Generated by Django 5.0.3 on 2024-03-27 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_anon_app", "0002_anonymizedinput_initialinput_anonymizedoutput_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=200)),
                ("pub_date", models.DateTimeField(verbose_name="time started")),
                ("use_case", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="anonymizedinput",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="llm_anon_app.session",
            ),
        ),
        migrations.AddField(
            model_name="anonymizedoutput",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="llm_anon_app.session",
            ),
        ),
        migrations.AddField(
            model_name="evalanswer",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="llm_anon_app.session",
            ),
        ),
        migrations.AddField(
            model_name="evalquestion",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="llm_anon_app.session",
            ),
        ),
        migrations.AddField(
            model_name="initialinput",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="llm_anon_app.session",
            ),
        ),
    ]
