# Generated by Django 5.0.3 on 2024-03-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_anon_app", "0003_session_anonymizedinput_session_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="use_case",
            field=models.CharField(default="", max_length=200),
        ),
    ]
