# Generated by Django 4.2.11 on 2024-04-06 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llm_anon_app', '0004_alter_session_use_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_case', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='evalquestion',
            name='anon_output',
        ),
        migrations.RemoveField(
            model_name='evalquestion',
            name='session',
        ),
        migrations.AddField(
            model_name='evalquestion',
            name='use_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='llm_anon_app.usecase'),
        ),
        migrations.AlterField(
            model_name='session',
            name='use_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='llm_anon_app.usecase'),
        ),
    ]
