# Generated by Django 4.2.11 on 2024-04-11 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llm_anon_app', '0005_usecase_remove_evalquestion_anon_output_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField()),
                ('use_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='llm_anon_app.usecase')),
            ],
        ),
    ]
